### ISSUE TITLE
problem with shapefile "powiaty"

### ISSUE THREAD

**Issue by fdepaolis** [kkopczewska/SPAG#1]
The R code produces an error on line#13
`pow<-readOGR(".","powiaty") # 380 NTS4 units`

Error in readOGR(".", "powiaty") : no features found
In addition: Warning message:
In ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  :
  ogrInfo: all features NULL

[It seems that the **powiaty.shp** file is missing]

**Comment by fdepaolis** [comment]
PLEASE DISREGARD THIS ISSUE.

**Comment by mythicalprogrammer** [comment]
How did you fix this? I got the same problem.
